# Generated by Django 3.1.6 on 2021-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundesliga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_matches', models.CharField(max_length=6400)),
                ('f_matches', models.CharField(max_length=6400)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaLiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_matches', models.CharField(max_length=6400)),
                ('f_matches', models.CharField(max_length=6400)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ligue_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_matches', models.CharField(max_length=6400)),
                ('f_matches', models.CharField(max_length=6400)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Premier_League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_matches', models.CharField(max_length=6400)),
                ('f_matches', models.CharField(max_length=6400)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ROTW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('f_matches', models.CharField(max_length=6400)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_matches', models.CharField(max_length=6400)),
                ('f_matches', models.CharField(max_length=6400)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
