# Generated by Django 2.2.3 on 2021-02-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundesliga',
            name='link',
        ),
        migrations.RemoveField(
            model_name='laliga',
            name='link',
        ),
        migrations.RemoveField(
            model_name='ligue_1',
            name='link',
        ),
        migrations.RemoveField(
            model_name='premier_league',
            name='link',
        ),
        migrations.RemoveField(
            model_name='rotw',
            name='link',
        ),
        migrations.RemoveField(
            model_name='serie_a',
            name='link',
        ),
    ]
